namespace: "alikins"
name: "collection_inspect"
version: "0.0.18"
license:
  - MIT
readme: "README.md"
authors:
  - "Adrian Likins <alikins@redhat.com>"
description: "A set of 'collection_inspect' plugins for debugging collection loading"
dependencies:
repository:
documentation:
homepage:
issues:
