namespace: "orionuser1"
name: "collection_simple_role"
version: "0.0.20"
license:
  - MIT
readme: "README.md"
authors:
  - "Orion User One <orionuser1@example.com>"
description: "A simple collection with a single role for testing purposes"
dependencies:
repository:
documentation:
homepage:
issues:
tags:
  - collectiontest
