namespace: "orionuser1"
name: "collection_simple_role"
version: "0.0.20"
license:
  - MIT
license_file: "LICENSE"
readme: "README.md"
authors:
  - "Orion User One <orionuser1@example.com>"
description: "A simple collection with a single role for testing purposes"
dependencies:
repository: "https://github.com/orionuser1/collection_simple_role"
documentation:
homepage:
issues:
tags:
  - collectiontest
